import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Service for managing application localization with manual JSON loading
class AppLocalizationService {
  static final AppLocalizationService _instance =
      AppLocalizationService._internal();
  static AppLocalizationService get instance => _instance;

  AppLocalizationService._internal();

  // Storage keys
  static const String _languageKey = 'app_language';
  static const String _defaultLanguage = 'en-US';

  // Current locale
  Locale _currentLocale = const Locale('en', 'US');

  /// Get current locale
  Locale get currentLocale => _currentLocale;

  /// Get current language code
  String get currentLanguageCode => _currentLocale.languageCode;

  /// Check if current locale is Traditional Chinese
  bool get isTraditionalChinese => _currentLocale.languageCode == 'zh';

  /// Initialize localization service
  Future<void> initialize() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLanguage = prefs.getString(_languageKey) ?? _defaultLanguage;
      await setLocale(savedLanguage);
      debugPrint(
          '✅ App localization initialized with language: $savedLanguage');
    } catch (e) {
      debugPrint('❌ Failed to initialize app localization: $e');
      // Fallback to default
      _currentLocale = const Locale('en', 'US');
    }
  }

  /// Set application locale
  Future<void> setLocale(String languageCode) async {
    try {
      Locale newLocale;

      switch (languageCode) {
        case 'zh-HK':
          newLocale = const Locale('zh', 'HK');
          break;
        case 'en-US':
        default:
          newLocale = const Locale('en', 'US');
          break;
      }

      _currentLocale = newLocale;

      // Save preference
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_languageKey, languageCode);

      debugPrint('✅ Locale set to: ${newLocale.toString()}');
    } catch (e) {
      debugPrint('❌ Failed to set locale: $e');
    }
  }

  /// Get translated string
  String translate(String key) {
    // Get translations for current locale
    final languageCode =
        '${_currentLocale.languageCode}-${_currentLocale.countryCode ?? ''}';

    // Load translations based on language code
    switch (languageCode) {
      case 'zh-HK':
        // Return hardcoded Traditional Chinese strings
        return _getChineseTranslation(key);
      case 'en-US':
        // Return hardcoded English strings
        return _getEnglishTranslation(key);
      default:
        return _getEnglishTranslation(key);
    }
  }

  /// Get English translation
  String _getEnglishTranslation(String key) {
    final translations = {
      'app_name': 'ScentSafe',
      'language': 'Language',
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'help': 'Help',
      'bluetooth': 'Bluetooth',
      'video': 'Video',
      'login': 'Login',
      'logout': 'Logout',
      'profile': 'Profile',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'error': 'Error',
      'warning': 'Warning',
      'info': 'Information',
      'success': 'Success',
      'loading': 'Loading...',
      'retry': 'Retry',
      'back': 'Back',
      'next': 'Next',
      'skip': 'Skip',
      'finish': 'Finish',
      'close': 'Close',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'refresh': 'Refresh',
      'share': 'Share',
      'copy': 'Copy',
      'paste': 'Paste',
      'select_all': 'Select All',
      'clear': 'Clear',
      'submit': 'Submit',
      'reset': 'Reset',
      'apply': 'Apply',
      'upload': 'Upload',
      'download': 'Download',
      'view': 'View',
      'add': 'Add',
      'remove': 'Remove',
      'update': 'Update',
      'create': 'Create',
      'read_more': 'Read More',
      'show_less': 'Show Less',
      'show_more': 'Show More',
      'expand': 'Expand',
      'collapse': 'Collapse',
      'open': 'Open',
      'welcome': 'Welcome',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'this_year': 'This Year',
      'all_time': 'All Time',
      'date': 'Date',
      'time': 'Time',
      'duration': 'Duration',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'on': 'On',
      'off': 'Off',
      'auto': 'Auto',
      'manual': 'Manual',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'normal': 'Normal',
      'fast': 'Fast',
      'slow': 'Slow',
      'driver_fatigue_detection': 'Driver Fatigue Detection',
      'fatigue_alert': 'Fatigue Alert',
      'drowsiness_detected': 'Drowsiness Detected',
      'attention_warning': 'Attention Warning',
      'eyes_closed': 'Eyes Closed',
      'head_pose': 'Head Pose',
      'yawning': 'Yawning',
      'blinking': 'Blinking',
      'microsleep': 'Microsleep',
      'alert_level': 'Alert Level',
      'safe': 'Safe',
      'caution': 'Caution',
      'danger': 'Danger',
      'critical': 'Critical',
      'detection_status': 'Detection Status',
      'camera_active': 'Camera Active',
      'camera_inactive': 'Camera Inactive',
      'monitoring': 'Monitoring',
      'not_monitoring': 'Not Monitoring',
      'start_monitoring': 'Start Monitoring',
      'stop_monitoring': 'Stop Monitoring',
      'pause_monitoring': 'Pause Monitoring',
      'resume_monitoring': 'Resume Monitoring',
      'alert_sound': 'Alert Sound',
      'alert_vibration': 'Alert Vibration',
      'alert_visual': 'Alert Visual',
      'alert_settings': 'Alert Settings',
      'sensitivity': 'Sensitivity',
      'threshold': 'Threshold',
      'adjust_sensitivity': 'Adjust Sensitivity',
      'calibration': 'Calibration',
      'calibrate': 'Calibrate',
      'calibration_complete': 'Calibration Complete',
      'calibration_failed': 'Calibration Failed',
      'aroma_therapy': 'Aroma Therapy',
      'aroma_device': 'Aroma Device',
      'aroma_level': 'Aroma Level',
      'aroma_intensity': 'Aroma Intensity',
      'aroma_duration': 'Aroma Duration',
      'connect_device': 'Connect Device',
      'disconnect_device': 'Disconnect Device',
      'device_connected': 'Device Connected',
      'device_disconnected': 'Device Disconnected',
      'device_not_found': 'Device Not Found',
      'bluetooth_enabled': 'Bluetooth Enabled',
      'bluetooth_disabled': 'Bluetooth Disabled',
      'scanning': 'Scanning...',
      'scan_complete': 'Scan Complete',
      'no_devices_found': 'No Devices Found',
      'select_device': 'Select Device',
      'pair_device': 'Pair Device',
      'unpair_device': 'Unpair Device',
      'device_settings': 'Device Settings',
      'device_info': 'Device Information',
      'device_name': 'Device Name',
      'device_id': 'Device ID',
      'battery_level': 'Battery Level',
      'signal_strength': 'Signal Strength',
      'connection_status': 'Connection Status',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'connecting': 'Connecting...',
      'pairing': 'Pairing...',
      'failed': 'Failed',
      'permissions': 'Permissions',
      'camera_permission': 'Camera Permission',
      'microphone_permission': 'Microphone Permission',
      'bluetooth_permission': 'Bluetooth Permission',
      'location_permission': 'Location Permission',
      'storage_permission': 'Storage Permission',
      'permission_required': 'Permission Required',
      'permission_denied': 'Permission Denied',
      'permission_granted': 'Permission Granted',
      'grant_permission': 'Grant Permission',
      'enable_permission': 'Enable Permission',
      'why_permission_needed': 'Why This Permission is Needed',
      'camera_permission_desc':
          'Camera access is required for driver fatigue detection and monitoring.',
      'bluetooth_permission_desc':
          'Bluetooth access is required to connect to aroma therapy devices.',
      'location_permission_desc':
          'Location access is required for Bluetooth device discovery.',
      'storage_permission_desc':
          'Storage access is required to save detection logs and settings.',
      'settings_general': 'General Settings',
      'settings_alerts': 'Alert Settings',
      'settings_device': 'Device Settings',
      'settings_account': 'Account Settings',
      'settings_privacy': 'Privacy Settings',
      'settings_about': 'About',
      'language_settings': 'Language Settings',
      'select_language': 'Select Language',
      'english': 'English',
      'traditional_chinese': 'Traditional Chinese',
      'theme_settings': 'Theme Settings',
      'light_theme': 'Light Theme',
      'dark_theme': 'Dark Theme',
      'system_theme': 'System Theme',
      'notification_settings': 'Notification Settings',
      'enable_notifications': 'Enable Notifications',
      'notification_sound': 'Notification Sound',
      'notification_vibration': 'Notification Vibration',
      'sound_settings': 'Sound Settings',
      'volume': 'Volume',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'voice_pack': 'Voice Pack',
      'voice_settings': 'Voice Settings',
      'enable_voice': 'Enable Voice',
      'voice_language': 'Voice Language',
      'voice_speed': 'Voice Speed',
      'voice_pitch': 'Voice Pitch',
      'account_info': 'Account Information',
      'user_name': 'User Name',
      'email': 'Email',
      'phone': 'Phone',
      'change_password': 'Change Password',
      'forgot_password': 'Forgot Password',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'create_account': 'Create Account',
      'already_have_account': 'Already Have an Account?',
      'dont_have_account': "Don't Have an Account?",
      'login_success': 'Login Successful',
      'login_failed': 'Login Failed',
      'logout_success': 'Logout Successful',
      'register_success': 'Registration Successful',
      'register_failed': 'Registration Failed',
      'invalid_credentials': 'Invalid Credentials',
      'email_required': 'Email is Required',
      'password_required': 'Password is Required',
      'password_too_short': 'Password is Too Short',
      'password_mismatch': 'Passwords Do Not Match',
      'email_invalid': 'Invalid Email Address',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'about_app': 'About ScentSafe',
      'version': 'Version',
      'build_number': 'Build Number',
      'developer': 'Developer',
      'contact_us': 'Contact Us',
      'support': 'Support',
      'feedback': 'Feedback',
      'rate_app': 'Rate App',
      'share_app': 'Share App',
      'help_center': 'Help Center',
      'faq': 'Frequently Asked Questions',
      'user_guide': 'User Guide',
      'troubleshooting': 'Troubleshooting',
      'getting_started': 'Getting Started',
      'how_to_use': 'How to Use',
      'quick_start': 'Quick Start',
      'tips': 'Tips',
      'best_practices': 'Best Practices',
      'safety_tips': 'Safety Tips',
      'driving_safety': 'Driving Safety',
      'fatigue_prevention': 'Fatigue Prevention',
      'take_break': 'Take a Break',
      'rest_recommended': 'Rest Recommended',
      'pull_over': 'Pull Over Safely',
      'stay_awake': 'Stay Awake',
      'drive_safe': 'Drive Safe',
      'arrive_safely': 'Arrive Safely',
      'emergency_contact': 'Emergency Contact',
      'emergency_services': 'Emergency Services',
      'call_emergency': 'Call Emergency',
      'report_incident': 'Report Incident',
      'incident_reported': 'Incident Reported',
      'logs': 'Logs',
      'detection_logs': 'Detection Logs',
      'alert_logs': 'Alert Logs',
      'activity_logs': 'Activity Logs',
      'export_logs': 'Export Logs',
      'clear_logs': 'Clear Logs',
      'log_details': 'Log Details',
      'statistics': 'Statistics',
      'analytics': 'Analytics',
      'performance': 'Performance',
      'accuracy': 'Accuracy',
      'response_time': 'Response Time',
      'detection_rate': 'Detection Rate',
      'false_positive_rate': 'False Positive Rate',
      'false_negative_rate': 'False Negative Rate',
      'total_detections': 'Total Detections',
      'total_alerts': 'Total Alerts',
      'avg_response_time': 'Average Response Time',
      'peak_hours': 'Peak Hours',
      'risk_factors': 'Risk Factors',
      'improvement_suggestions': 'Improvement Suggestions',
      'data_sync': 'Data Sync',
      'sync_now': 'Sync Now',
      'last_sync': 'Last Sync',
      'sync_failed': 'Sync Failed',
      'sync_complete': 'Sync Complete',
      'cloud_backup': 'Cloud Backup',
      'backup_now': 'Backup Now',
      'restore_backup': 'Restore Backup',
      'backup_complete': 'Backup Complete',
      'restore_complete': 'Restore Complete',
      'storage_used': 'Storage Used',
      'storage_available': 'Storage Available',
      'clear_cache': 'Clear Cache',
      'clear_data': 'Clear Data',
      'data_cleared': 'Data Cleared',
      'delete_account': 'Delete Account',
      'account_deleted': 'Account Deleted',
      'confirm_delete': 'Confirm Delete',
      'are_you_sure': 'Are You Sure?',
      'this_action_cannot_be_undone': 'This Action Cannot Be Undone',
      'please_wait': 'Please Wait...',
      'processing': 'Processing...',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'network_error': 'Network Error',
      'server_error': 'Server Error',
      'unknown_error': 'Unknown Error',
      'try_again': 'Try Again',
      'check_connection': 'Check Your Connection',
      'no_internet': 'No Internet Connection',
      'internet_connected': 'Internet Connected',
      'update_available': 'Update Available',
      'update_now': 'Update Now',
      'update_later': 'Update Later',
      'up_to_date': 'Up to Date',
      'maintenance_mode': 'Maintenance Mode',
      'service_unavailable': 'Service Unavailable',
      'coming_soon': 'Coming Soon',
      'beta': 'Beta',
      'experimental': 'Experimental',
      'new_feature': 'New Feature',
      'improvement': 'Improvement',
      'bug_fix': 'Bug Fix',
      'security_update': 'Security Update',
      'currency_hkd': 'HKD',
      'currency_format': 'HKD {amount}',
      'date_format_short': 'dd/MM/yyyy',
      'date_format_long': 'EEEE, dd MMMM yyyy',
      'time_format_12h': 'h:mm a',
      'time_format_24h': 'HH:mm',
      'datetime_format': 'dd/MM/yyyy HH:mm',
      'week_start': 'Monday',
      'weekend_days': 'Saturday, Sunday',
      'working_hours': '09:00 - 18:00',
      'timezone': 'Hong Kong Time (HKT)',
      'timezone_abbreviation': 'HKT',
      'utc_offset': 'UTC+8',
      // Additional keys for dashboard
      'hello': 'Hello',
      'tap_to_expand': 'Tap to expand',
      'alert': 'Alert',
      'mild_fatigue': 'Mild Fatigue',
      'moderate_fatigue': 'Moderate Fatigue',
      'severe_fatigue': 'Severe Fatigue',
      'initializing': 'Initializing...',
      'awakeness_level': 'Awakeness Level',
      'current_scent': 'Current Scent',
      'view_all': 'View All',
      'stopping_camera': 'Stopping camera...',
      'starting_camera': 'Starting camera...',
      'failed_to_initialize_camera': 'Failed to initialize camera',
      'selected_voice_pack': 'Selected',
      'camera_off': 'Camera Off',
      'use_toolbar_button': 'Use toolbar button to control camera',
      'frequently_asked_questions': 'Frequently Asked Questions',
      'browse_documentation': 'Browse comprehensive documentation',
      'contact_support': 'Contact Support',
      'email_support': 'Email Support',
      'support_email': 'support@scentsafe.com',
      'phone_support': 'Phone Support',
      'support_phone': '+1 (555) 123-4567',
      'website': 'Website',
      'support_website': 'www.scentsafe.com',
      'response_time': 'We typically respond within 24 hours.',
      'support_hours': 'Available Mon-Fri, 9AM-6PM EST.',
      'visit_website': 'Visit us for documentation and guides.',
      'copied_to_clipboard': 'Copied to clipboard!',
      'logout_confirmation':
          'Are you sure you want to log out? You will need to sign in again to access your account.',
    };
    return translations[key] ?? key;
  }

  /// Get Traditional Chinese translation
  String _getChineseTranslation(String key) {
    final translations = {
      'app_name': 'ScentSafe',
      'language': '語言',
      'settings': '設定',
      'dashboard': '儀表板',
      'help': '幫助',
      'bluetooth': '藍牙',
      'video': '影片',
      'login': '登入',
      'logout': '登出',
      'profile': '個人資料',
      'save': '儲存',
      'cancel': '取消',
      'delete': '刪除',
      'edit': '編輯',
      'confirm': '確認',
      'yes': '是',
      'no': '否',
      'ok': '確定',
      'error': '錯誤',
      'warning': '警告',
      'info': '資訊',
      'success': '成功',
      'loading': '載入中...',
      'retry': '重試',
      'back': '返回',
      'next': '下一步',
      'skip': '跳過',
      'finish': '完成',
      'close': '關閉',
      'search': '搜尋',
      'filter': '篩選',
      'sort': '排序',
      'refresh': '重新整理',
      'share': '分享',
      'copy': '複製',
      'paste': '貼上',
      'select_all': '全選',
      'clear': '清除',
      'submit': '提交',
      'reset': '重設',
      'apply': '套用',
      'upload': '上傳',
      'download': '下載',
      'view': '檢視',
      'add': '新增',
      'remove': '移除',
      'update': '更新',
      'create': '建立',
      'read_more': '閱讀更多',
      'show_less': '顯示較少',
      'show_more': '顯示更多',
      'expand': '展開',
      'collapse': '收合',
      'open': '開啟',
      'welcome': '歡迎',
      'good_morning': '早安',
      'good_afternoon': '午安',
      'good_evening': '晚安',
      'today': '今天',
      'yesterday': '昨天',
      'tomorrow': '明天',
      'this_week': '本週',
      'this_month': '本月',
      'this_year': '今年',
      'all_time': '全部時間',
      'date': '日期',
      'time': '時間',
      'duration': '持續時間',
      'status': '狀態',
      'active': '啟用',
      'inactive': '停用',
      'enabled': '已啟用',
      'disabled': '已停用',
      'on': '開啟',
      'off': '關閉',
      'auto': '自動',
      'manual': '手動',
      'high': '高',
      'medium': '中',
      'low': '低',
      'normal': '正常',
      'fast': '快',
      'slow': '慢',
      'driver_fatigue_detection': '駕駛疲勞偵測',
      'fatigue_alert': '疲勞警報',
      'drowsiness_detected': '偵測到睡意',
      'attention_warning': '注意力警告',
      'eyes_closed': '閉眼',
      'head_pose': '頭部姿勢',
      'yawning': '打哈欠',
      'blinking': '眨眼',
      'microsleep': '微睡眠',
      'alert_level': '警報等級',
      'safe': '安全',
      'caution': '注意',
      'danger': '危險',
      'critical': '嚴重',
      'detection_status': '偵測狀態',
      'camera_active': '相機啟用',
      'camera_inactive': '相機停用',
      'monitoring': '監控中',
      'not_monitoring': '未監控',
      'start_monitoring': '開始監控',
      'stop_monitoring': '停止監控',
      'pause_monitoring': '暫停監控',
      'resume_monitoring': '恢復監控',
      'alert_sound': '警報聲音',
      'alert_vibration': '警報震動',
      'alert_visual': '視覺警報',
      'alert_settings': '警報設定',
      'sensitivity': '靈敏度',
      'threshold': '閾值',
      'adjust_sensitivity': '調整靈敏度',
      'calibration': '校準',
      'calibrate': '校準',
      'calibration_complete': '校準完成',
      'calibration_failed': '校準失敗',
      'aroma_therapy': '香薰療法',
      'aroma_device': '香薰裝置',
      'aroma_level': '香薰等級',
      'aroma_intensity': '香薰強度',
      'aroma_duration': '香薰持續時間',
      'connect_device': '連接裝置',
      'disconnect_device': '中斷裝置',
      'device_connected': '裝置已連接',
      'device_disconnected': '裝置已中斷',
      'device_not_found': '找不到裝置',
      'bluetooth_enabled': '藍牙已啟用',
      'bluetooth_disabled': '藍牙已停用',
      'scanning': '掃描中...',
      'scan_complete': '掃描完成',
      'no_devices_found': '找不到裝置',
      'select_device': '選擇裝置',
      'pair_device': '配對裝置',
      'unpair_device': '解除配對',
      'device_settings': '裝置設定',
      'device_info': '裝置資訊',
      'device_name': '裝置名稱',
      'device_id': '裝置 ID',
      'battery_level': '電量',
      'signal_strength': '訊號強度',
      'connection_status': '連接狀態',
      'connected': '已連接',
      'disconnected': '已中斷',
      'connecting': '連接中...',
      'pairing': '配對中...',
      'failed': '失敗',
      'permissions': '權限',
      'camera_permission': '相機權限',
      'microphone_permission': '麥克風權限',
      'bluetooth_permission': '藍牙權限',
      'location_permission': '位置權限',
      'storage_permission': '儲存權限',
      'permission_required': '需要權限',
      'permission_denied': '權限被拒絕',
      'permission_granted': '權限已授予',
      'grant_permission': '授予權限',
      'enable_permission': '啟用權限',
      'why_permission_needed': '為什麼需要此權限',
      'camera_permission_desc': '需要相機存取權限以進行駕駛疲勞偵測和監控。',
      'bluetooth_permission_desc': '需要藍牙存取權限以連接香薰療法裝置。',
      'location_permission_desc': '需要位置存取權限以進行藍牙裝置探索。',
      'storage_permission_desc': '需要儲存存取權限以儲存偵測記錄和設定。',
      'settings_general': '一般設定',
      'settings_alerts': '警報設定',
      'settings_device': '裝置設定',
      'settings_account': '帳戶設定',
      'settings_privacy': '隱私設定',
      'settings_about': '關於',
      'language_settings': '語言設定',
      'select_language': '選擇語言',
      'english': 'English',
      'traditional_chinese': '繁體中文',
      'theme_settings': '主題設定',
      'light_theme': '淺色主題',
      'dark_theme': '深色主題',
      'system_theme': '系統主題',
      'notification_settings': '通知設定',
      'enable_notifications': '啟用通知',
      'notification_sound': '通知聲音',
      'notification_vibration': '通知震動',
      'sound_settings': '聲音設定',
      'volume': '音量',
      'mute': '靜音',
      'unmute': '取消靜音',
      'voice_pack': '語音包',
      'voice_settings': '語音設定',
      'enable_voice': '啟用語音',
      'voice_language': '語音語言',
      'voice_speed': '語音速度',
      'voice_pitch': '語音音調',
      'account_info': '帳戶資訊',
      'user_name': '使用者名稱',
      'email': '電子郵件',
      'phone': '電話',
      'change_password': '變更密碼',
      'forgot_password': '忘記密碼',
      'sign_in': '登入',
      'sign_up': '註冊',
      'sign_out': '登出',
      'create_account': '建立帳戶',
      'already_have_account': '已有帳戶？',
      'dont_have_account': '沒有帳戶？',
      'login_success': '登入成功',
      'login_failed': '登入失敗',
      'logout_success': '登出成功',
      'register_success': '註冊成功',
      'register_failed': '註冊失敗',
      'invalid_credentials': '無效的憑證',
      'email_required': '需要電子郵件',
      'password_required': '需要密碼',
      'password_too_short': '密碼太短',
      'password_mismatch': '密碼不符',
      'email_invalid': '無效的電子郵件地址',
      'privacy_policy': '隱私權政策',
      'terms_of_service': '服務條款',
      'about_app': '關於 ScentSafe',
      'version': '版本',
      'build_number': '建置編號',
      'developer': '開發者',
      'contact_us': '聯絡我們',
      'support': '支援',
      'feedback': '意見回饋',
      'rate_app': '評分應用程式',
      'share_app': '分享應用程式',
      'help_center': '說明中心',
      'faq': '常見問題',
      'user_guide': '使用者指南',
      'troubleshooting': '疑難排解',
      'getting_started': '快速入門',
      'how_to_use': '如何使用',
      'quick_start': '快速開始',
      'tips': '小貼士',
      'best_practices': '最佳實務',
      'safety_tips': '安全小貼士',
      'driving_safety': '駕駛安全',
      'fatigue_prevention': '疲勞預防',
      'take_break': '休息一下',
      'rest_recommended': '建議休息',
      'pull_over': '安全靠邊停車',
      'stay_awake': '保持清醒',
      'drive_safe': '安全駕駛',
      'arrive_safely': '安全到達',
      'emergency_contact': '緊急聯絡人',
      'emergency_services': '緊急服務',
      'call_emergency': '撥打緊急電話',
      'report_incident': '報告事件',
      'incident_reported': '事件已報告',
      'logs': '記錄',
      'detection_logs': '偵測記錄',
      'alert_logs': '警報記錄',
      'activity_logs': '活動記錄',
      'export_logs': '匯出記錄',
      'clear_logs': '清除記錄',
      'log_details': '記錄詳情',
      'statistics': '統計資料',
      'analytics': '分析',
      'performance': '效能',
      'accuracy': '準確度',
      'response_time': '回應時間',
      'detection_rate': '偵測率',
      'false_positive_rate': '誤報率',
      'false_negative_rate': '漏報率',
      'total_detections': '總偵測次數',
      'total_alerts': '總警報次數',
      'avg_response_time': '平均回應時間',
      'peak_hours': '尖峰時段',
      'risk_factors': '風險因素',
      'improvement_suggestions': '改善建議',
      'data_sync': '資料同步',
      'sync_now': '立即同步',
      'last_sync': '上次同步',
      'sync_failed': '同步失敗',
      'sync_complete': '同步完成',
      'cloud_backup': '雲端備份',
      'backup_now': '立即備份',
      'restore_backup': '還原備份',
      'backup_complete': '備份完成',
      'restore_complete': '還原完成',
      'storage_used': '已使用儲存空間',
      'storage_available': '可用儲存空間',
      'clear_cache': '清除快取',
      'clear_data': '清除資料',
      'data_cleared': '資料已清除',
      'delete_account': '刪除帳戶',
      'account_deleted': '帳戶已刪除',
      'confirm_delete': '確認刪除',
      'are_you_sure': '您確定嗎？',
      'this_action_cannot_be_undone': '此操作無法復原',
      'please_wait': '請稍候...',
      'processing': '處理中...',
      'completed': '已完成',
      'cancelled': '已取消',
      'network_error': '網路錯誤',
      'server_error': '伺服器錯誤',
      'unknown_error': '未知錯誤',
      'try_again': '再試一次',
      'check_connection': '檢查您的連線',
      'no_internet': '沒有網路連線',
      'internet_connected': '網路已連線',
      'update_available': '有可用更新',
      'update_now': '立即更新',
      'update_later': '稍後更新',
      'up_to_date': '已是最新版本',
      'maintenance_mode': '維護模式',
      'service_unavailable': '服務無法使用',
      'coming_soon': '即將推出',
      'beta': '測試版',
      'experimental': '實驗性',
      'new_feature': '新功能',
      'improvement': '改善',
      'bug_fix': '錯誤修正',
      'security_update': '安全性更新',
      'currency_hkd': 'HKD',
      'currency_format': 'HKD {amount}',
      'date_format_short': 'dd/MM/yyyy',
      'date_format_long': 'EEEE, dd MMMM yyyy',
      'time_format_12h': 'h:mm a',
      'time_format_24h': 'HH:mm',
      'datetime_format': 'dd/MM/yyyy HH:mm',
      'week_start': '星期一',
      'weekend_days': '星期六、星期日',
      'working_hours': '09:00 - 18:00',
      'timezone': '香港時間 (HKT)',
      'timezone_abbreviation': 'HKT',
      'utc_offset': 'UTC+8',
      // Additional keys for dashboard
      'hello': '您好',
      'tap_to_expand': '點擊展開',
      'alert': '警報',
      'mild_fatigue': '輕度疲勞',
      'moderate_fatigue': '中度疲勞',
      'severe_fatigue': '嚴重疲勞',
      'initializing': '初始化中...',
      'awakeness_level': '清醒程度',
      'current_scent': '當前香薰',
      'view_all': '檢視全部',
      'stopping_camera': '停止相機中...',
      'starting_camera': '啟動相機中...',
      'failed_to_initialize_camera': '相機初始化失敗',
      'selected_voice_pack': '已選擇',
      'camera_off': '相機已關閉',
      'use_toolbar_button': '使用工具列按鈕控制相機',
      'frequently_asked_questions': '常見問題',
      'browse_documentation': '瀏覽完整文件',
      'contact_support': '聯絡支援',
      'email_support': '電子郵件支援',
      'support_email': 'support@scentsafe.com',
      'phone_support': '電話支援',
      'support_phone': '+1 (555) 123-4567',
      'website': '網站',
      'support_website': 'www.scentsafe.com',
      'response_time': '我們通常在 24 小時內回覆。',
      'support_hours': '週一至週五，上午 9 點至下午 6 點。',
      'visit_website': '造訪我們以獲取文件和指南。',
      'copied_to_clipboard': '已複製到剪貼簿！',
      'logout_confirmation': '您確定要登出嗎？您需要再次登入才能存取您的帳戶。',
    };
    return translations[key] ?? key;
  }
}
